data_threshold: 200000
n_steps: 600000
n_datapoints: 100000
delta_t : 1.0

length_of_microtubule: 100
n_microtubules: 1

seed : 4194326

p_mutant: 0.1
mutant_affinity: 0.4

motor_speed : 1.0
k_off : 0.0003
c_motor : 1.0
k_on : 0.0003

alpha: 0.2
beta: 0.1

