---
seed: 329954438
n_steps: 2000000
n_datapoints: 100000
data_threshold: 0
delta_t: 5e-06
kbT: 4.114
eta: 0.001
microtubules:
  count: 2
  length: 500
  y_dist: 32
  site_size: 8
  radius: 12.5
  elevation: 50
  start_coord:
    - 0
    - 0
  imposed_velocity:
    - 0
    - 0
  immobile_until:
    - 9500
    - 50
  printout: false
  diffusion: false
motors:
  k_on_i: 0.02
  k_on_ii: 0.02
  concentration: 1.5
  conc_eff_bind: 700000
  k_off_i: 600
  k_off_ii: 15
  velocity: 650
  diffusion_const: 0.0024
  tethers_active: true
  k_tether_free: 0.1
  conc_eff_tether: 100
  k_untether_free: 0.025
  k_untether: 0.068
  r_0: 120
  k_spring: 0.3
  k_slack: 0.05
  stall_force: 5
xlinks:
  k_on: 0.0022
  concentration: 2.0    # 0.2
  conc_eff_bind: 750
  k_off_i: 0.132
  k_off_ii: 0.132
  diffusion_const_i: 0.036
  diffusion_const_ii: 0.018
  r_0: 32
  k_spring: 0.207
