data_threshold: 400000
n_steps: 1000000
n_datapoints: 100000
delta_t : 0.00005

n_microtubules: 2
length_of_microtubule: 140

seed : 3299515

switch_rate : 0.1
motor_speed : 62.5
c_motor : 200
k_on : 0.00027
k_off : 0.169

alpha: 0.0
beta: 0.0

