data_threshold: 4000000
n_steps: 10000000
n_datapoints: 100000
delta_t : 0.005

n_microtubules: 2
length_of_microtubule: 1000

seed : 3298615

switch_rate : 0.10
motor_speed : 62.5
c_motor : 200
k_on : 0.00027
k_off : 0.169

alpha: 0.3
beta: 0.05

