---
seed: 329954433
n_steps: 10000000
n_datapoints: 10000
data_threshold: 0
delta_t: 1e-05
kbT: 4.114
eta: 0.001
microtubules:
  count: 2
  length: 500
  y_dist: 32
  site_size: 8
  radius: 12.5
  elevation: 50
  start_coord:
    - 0
    - 0
  imposed_velocity:
    - 0
    - 0
  immobile_until:
    - 9500
    - 500
  printout: false
  diffusion: true
motors:
  k_on: 0.02
  c_bulk: 1.5
  c_eff_bind: 250000
  k_on_ATP: 2500
  c_ATP: 2
  k_hydrolyze: 95
  k_off_i: 40
  k_off_ii: 100
  endpausing_active: true
  tethers_active: true
  k_tether: 0.5
  c_eff_tether: 100
  k_untether: 0.05
  r_0: 120
  k_spring: 0.3
  k_slack: 0.06
  stall_force: 5
xlinks:
  k_on: 0.0022
  concentration: 0.2
  conc_eff_bind: 750
  k_off_i: 0.132
  k_off_ii: 0.132
  diffusion_const_i: 0.036
  diffusion_const_ii: 0.018
  r_0: 32
  k_spring: 0.207
