seed: 329954433
n_steps: 100000000
n_datapoints: 100000
data_threshold: 0
delta_t: 1e-05
kbT: 4.114
eta: 0.001
microtubules:
  count: 2
  length: 125
  y_dist: 32
  site_size: 8
  radius: 12.5
  elevation: 50
  start_coord:
  - 0
  - 0
  imposed_velocity:
  - 0
  - 0
  immobile_until:
  - 9500
  - 500
  printout: false
  diffusion: true
motors:
  k_on: 0.02
  c_bulk: 6
  c_eff_bind: 250000
  k_on_ATP: 2500
  c_ATP: 2
  k_hydrolyze: 110
  k_off_i: 30
  k_off_ii: 180
  k_tether: 0.00167
  c_eff_tether: 100
  k_untether: 0.5
  r_0: 120
  k_spring: 0.1325
  k_slack: 0.0265
  stall_force: 6
  applied_force: 0
  tethers_active: true
  endpausing_active: true
xlinks:
  k_on: 0.0022
  concentration: 0.5
  conc_eff_bind: 750
  k_off_i: 0.132
  k_off_ii: 0.132
  diffusion_const_i: 0.036
  diffusion_const_ii: 0.018
  r_0: 32
  k_spring: 0.207
