seed: 329951224
n_steps: 2000000
n_datapoints: 100000
data_threshold: 0   # dont rly use this anymore; want all steps for movie
delta_t: 0.0005   #0.000005
kbT: 4.114
eta_inverse: 1000
mt_radius: 12.5
mt_height: 50
site_size: 8

length_of_microtubule: 250
n_microtubules: 1
mt_printout: false               # Toggles real-time ASCII printout
bot_mt_start_coord: 0           # 'First' MT; plus-end on right
top_mt_start_coord: 0           # 'Second' MT; plus-end on left
top_mt_imposed_velocity: 0
bot_mt_pinned: true             # Toggles immobilization of 1st MT
top_mt_pinned_until: 10         # 2nd MT immobilized until this time (s) 

k_on_motor: 0.0035
c_motor: 1.5
c_eff_motor_bind: 5000
k_off_motor: 0.20
k_off_pseudo: 10     #2 for d  # 0.5 for c
k_off_ratio: 5       #1 for d   #25 for b
motor_speed: 600
failstep_rate: 5  #2 for c   #0.1 for b
D_motor: 0.0024
k_tether_free: 0.007
c_eff_motor_teth: 1000
k_untether: 0.068
k_untether_free: 0.034
r_0_motor: 120
k_spring_motor: 0.3
k_slack_motor: 0.005
stall_force: 5
switch_rate: 0          # obsolete; don't rly use anymore
alpha: 0
beta: 0

k_on_xlink: 0.01136
c_xlink: 0.4
k_off_xlink_i: 0.09091  
k_off_xlink_ii: 0.0455   
D_xlink_i: 0.0058
D_xlink_ii: 0.0029
c_eff_xlink: 5000
r_0_xlink: 32
k_spring_xlink: 0.207
