seed: 329951224
n_steps: 5000000
n_datapoints: 100000
data_threshold: 1000000
delta_t: 0.01
kbT: 4.114
eta_inverse: 1000
n_microtubules: 2
length_of_microtubule: 250
top_mt_start_coord: 0
bot_mt_start_coord: 125
top_mt_imposed_velocity: 80
mt_radius: 12.5
mt_height: 50
site_size: 8
k_on_motor: 0.0035
c_motor: 6
c_eff_motor_bind: 15000
k_off_motor: 0.20
k_off_pseudo: 0.5
k_off_ratio: 4
motor_speed: 300
failstep_rate: 0.5
D_motor: 0.0024
k_tether_free: 0.00027
c_eff_motor: 1000
k_untether: 0.068
k_untether_free: 0.034
r_0_motor: 120
k_spring_motor: 0.3
k_slack_motor: 0.005
stall_force: 5
switch_rate: 0
alpha: 0
beta: 0
k_on_xlink: 0.01136
c_xlink: 0.4
k_off_xlink_i: 0.09091
k_off_xlink_ii: 0.0455
D_xlink_i: 0.0058
D_xlink_ii: 0.0029
c_eff_xlink: 1000
r_0_xlink: 32
k_spring_xlink: 0.207
