seed: 329954438
n_steps: 20000000
n_datapoints: 100000
data_threshold: 0   # dont use this anymore; want all steps for movie
delta_t: 0.00005

kbT: 4.114
eta: 0.001

microtubules:
    count: 2
    length: 500
    y_dist: 32
    site_size: 8
    radius: 12.5
    elevation: 50 
    start_coord: [0, 0] 
    imposed_velocity: [0, 0]  # currently disabled
    immobile_until: [9500, 500]
    printout: false
    diffusion: true

motors:
    k_on_i: 0.02
    k_on_ii: 0.02
    concentration: 1.5 #0 #0.05
    conc_eff_bind: 800000
    k_off_i: 600
    k_off_ii: 15 #5 #10 #15
    velocity: 650
    diffusion_const: 0.0024
    k_off_ratio: 1
    failstep_rate: 0 #0.5
    k_tether_free: 0 #0.0005
    conc_eff_tether: 0 #2000
    k_untether_free: 0.025
    k_untether: 0.068
    r_0: 120
    k_spring: 0.3
    k_slack: 0.05
    stall_force: 5

xlinks:
    k_on: 0.0022
    concentration: 0.4 #0.01 #0.05 #0.2
    conc_eff_bind: 2500
    k_off_i: 0.132
    k_off_ii: 0.132
    diffusion_const_i: 0.038
    diffusion_const_ii: 0.019
    r_0: 32
    k_spring: 0.207
